# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /mnt/c/Users/DELL/code/gui

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /mnt/c/Users/DELL/code/gui

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components

.PHONY : list_install_components/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/DELL/code/gui/CMakeFiles /mnt/c/Users/DELL/code/gui/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /mnt/c/Users/DELL/code/gui/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named main

# Build rule for target.
main: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 main
.PHONY : main

# fast build rule for target.
main/fast:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/build
.PHONY : main/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) -f inc/glfw/CMakeFiles/uninstall.dir/build.make inc/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) -f inc/glfw/src/CMakeFiles/glfw.dir/build.make inc/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named wave

# Build rule for target.
wave: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 wave
.PHONY : wave

# fast build rule for target.
wave/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/wave.dir/build.make inc/glfw/examples/CMakeFiles/wave.dir/build
.PHONY : wave/fast

#=============================================================================
# Target rules for targets named simple

# Build rule for target.
simple: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 simple
.PHONY : simple

# fast build rule for target.
simple/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/simple.dir/build.make inc/glfw/examples/CMakeFiles/simple.dir/build
.PHONY : simple/fast

#=============================================================================
# Target rules for targets named gears

# Build rule for target.
gears: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gears
.PHONY : gears

# fast build rule for target.
gears/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/gears.dir/build.make inc/glfw/examples/CMakeFiles/gears.dir/build
.PHONY : gears/fast

#=============================================================================
# Target rules for targets named boing

# Build rule for target.
boing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 boing
.PHONY : boing

# fast build rule for target.
boing/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/boing.dir/build.make inc/glfw/examples/CMakeFiles/boing.dir/build
.PHONY : boing/fast

#=============================================================================
# Target rules for targets named heightmap

# Build rule for target.
heightmap: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 heightmap
.PHONY : heightmap

# fast build rule for target.
heightmap/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/heightmap.dir/build.make inc/glfw/examples/CMakeFiles/heightmap.dir/build
.PHONY : heightmap/fast

#=============================================================================
# Target rules for targets named splitview

# Build rule for target.
splitview: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 splitview
.PHONY : splitview

# fast build rule for target.
splitview/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/splitview.dir/build.make inc/glfw/examples/CMakeFiles/splitview.dir/build
.PHONY : splitview/fast

#=============================================================================
# Target rules for targets named offscreen

# Build rule for target.
offscreen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 offscreen
.PHONY : offscreen

# fast build rule for target.
offscreen/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/offscreen.dir/build.make inc/glfw/examples/CMakeFiles/offscreen.dir/build
.PHONY : offscreen/fast

#=============================================================================
# Target rules for targets named particles

# Build rule for target.
particles: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 particles
.PHONY : particles

# fast build rule for target.
particles/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/particles.dir/build.make inc/glfw/examples/CMakeFiles/particles.dir/build
.PHONY : particles/fast

#=============================================================================
# Target rules for targets named sharing

# Build rule for target.
sharing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 sharing
.PHONY : sharing

# fast build rule for target.
sharing/fast:
	$(MAKE) -f inc/glfw/examples/CMakeFiles/sharing.dir/build.make inc/glfw/examples/CMakeFiles/sharing.dir/build
.PHONY : sharing/fast

#=============================================================================
# Target rules for targets named title

# Build rule for target.
title: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 title
.PHONY : title

# fast build rule for target.
title/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/title.dir/build.make inc/glfw/tests/CMakeFiles/title.dir/build
.PHONY : title/fast

#=============================================================================
# Target rules for targets named timeout

# Build rule for target.
timeout: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 timeout
.PHONY : timeout

# fast build rule for target.
timeout/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/timeout.dir/build.make inc/glfw/tests/CMakeFiles/timeout.dir/build
.PHONY : timeout/fast

#=============================================================================
# Target rules for targets named monitors

# Build rule for target.
monitors: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 monitors
.PHONY : monitors

# fast build rule for target.
monitors/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/monitors.dir/build.make inc/glfw/tests/CMakeFiles/monitors.dir/build
.PHONY : monitors/fast

#=============================================================================
# Target rules for targets named clipboard

# Build rule for target.
clipboard: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 clipboard
.PHONY : clipboard

# fast build rule for target.
clipboard/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/clipboard.dir/build.make inc/glfw/tests/CMakeFiles/clipboard.dir/build
.PHONY : clipboard/fast

#=============================================================================
# Target rules for targets named cursor

# Build rule for target.
cursor: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cursor
.PHONY : cursor

# fast build rule for target.
cursor/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/cursor.dir/build.make inc/glfw/tests/CMakeFiles/cursor.dir/build
.PHONY : cursor/fast

#=============================================================================
# Target rules for targets named msaa

# Build rule for target.
msaa: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 msaa
.PHONY : msaa

# fast build rule for target.
msaa/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/msaa.dir/build.make inc/glfw/tests/CMakeFiles/msaa.dir/build
.PHONY : msaa/fast

#=============================================================================
# Target rules for targets named glfwinfo

# Build rule for target.
glfwinfo: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 glfwinfo
.PHONY : glfwinfo

# fast build rule for target.
glfwinfo/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/glfwinfo.dir/build.make inc/glfw/tests/CMakeFiles/glfwinfo.dir/build
.PHONY : glfwinfo/fast

#=============================================================================
# Target rules for targets named threads

# Build rule for target.
threads: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 threads
.PHONY : threads

# fast build rule for target.
threads/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/threads.dir/build.make inc/glfw/tests/CMakeFiles/threads.dir/build
.PHONY : threads/fast

#=============================================================================
# Target rules for targets named reopen

# Build rule for target.
reopen: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 reopen
.PHONY : reopen

# fast build rule for target.
reopen/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/reopen.dir/build.make inc/glfw/tests/CMakeFiles/reopen.dir/build
.PHONY : reopen/fast

#=============================================================================
# Target rules for targets named triangle-vulkan

# Build rule for target.
triangle-vulkan: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 triangle-vulkan
.PHONY : triangle-vulkan

# fast build rule for target.
triangle-vulkan/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/triangle-vulkan.dir/build.make inc/glfw/tests/CMakeFiles/triangle-vulkan.dir/build
.PHONY : triangle-vulkan/fast

#=============================================================================
# Target rules for targets named opacity

# Build rule for target.
opacity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 opacity
.PHONY : opacity

# fast build rule for target.
opacity/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/opacity.dir/build.make inc/glfw/tests/CMakeFiles/opacity.dir/build
.PHONY : opacity/fast

#=============================================================================
# Target rules for targets named iconify

# Build rule for target.
iconify: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 iconify
.PHONY : iconify

# fast build rule for target.
iconify/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/iconify.dir/build.make inc/glfw/tests/CMakeFiles/iconify.dir/build
.PHONY : iconify/fast

#=============================================================================
# Target rules for targets named gamma

# Build rule for target.
gamma: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 gamma
.PHONY : gamma

# fast build rule for target.
gamma/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/gamma.dir/build.make inc/glfw/tests/CMakeFiles/gamma.dir/build
.PHONY : gamma/fast

#=============================================================================
# Target rules for targets named events

# Build rule for target.
events: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 events
.PHONY : events

# fast build rule for target.
events/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/events.dir/build.make inc/glfw/tests/CMakeFiles/events.dir/build
.PHONY : events/fast

#=============================================================================
# Target rules for targets named icon

# Build rule for target.
icon: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 icon
.PHONY : icon

# fast build rule for target.
icon/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/icon.dir/build.make inc/glfw/tests/CMakeFiles/icon.dir/build
.PHONY : icon/fast

#=============================================================================
# Target rules for targets named joysticks

# Build rule for target.
joysticks: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 joysticks
.PHONY : joysticks

# fast build rule for target.
joysticks/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/joysticks.dir/build.make inc/glfw/tests/CMakeFiles/joysticks.dir/build
.PHONY : joysticks/fast

#=============================================================================
# Target rules for targets named windows

# Build rule for target.
windows: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 windows
.PHONY : windows

# fast build rule for target.
windows/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/windows.dir/build.make inc/glfw/tests/CMakeFiles/windows.dir/build
.PHONY : windows/fast

#=============================================================================
# Target rules for targets named empty

# Build rule for target.
empty: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 empty
.PHONY : empty

# fast build rule for target.
empty/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/empty.dir/build.make inc/glfw/tests/CMakeFiles/empty.dir/build
.PHONY : empty/fast

#=============================================================================
# Target rules for targets named inputlag

# Build rule for target.
inputlag: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 inputlag
.PHONY : inputlag

# fast build rule for target.
inputlag/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/inputlag.dir/build.make inc/glfw/tests/CMakeFiles/inputlag.dir/build
.PHONY : inputlag/fast

#=============================================================================
# Target rules for targets named tearing

# Build rule for target.
tearing: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 tearing
.PHONY : tearing

# fast build rule for target.
tearing/fast:
	$(MAKE) -f inc/glfw/tests/CMakeFiles/tearing.dir/build.make inc/glfw/tests/CMakeFiles/tearing.dir/build
.PHONY : tearing/fast

inc/glfw/deps/glad_gl.o: inc/glfw/deps/glad_gl.c.o

.PHONY : inc/glfw/deps/glad_gl.o

# target to build an object file
inc/glfw/deps/glad_gl.c.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/inc/glfw/deps/glad_gl.c.o
.PHONY : inc/glfw/deps/glad_gl.c.o

inc/glfw/deps/glad_gl.i: inc/glfw/deps/glad_gl.c.i

.PHONY : inc/glfw/deps/glad_gl.i

# target to preprocess a source file
inc/glfw/deps/glad_gl.c.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/inc/glfw/deps/glad_gl.c.i
.PHONY : inc/glfw/deps/glad_gl.c.i

inc/glfw/deps/glad_gl.s: inc/glfw/deps/glad_gl.c.s

.PHONY : inc/glfw/deps/glad_gl.s

# target to generate assembly for a file
inc/glfw/deps/glad_gl.c.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/inc/glfw/deps/glad_gl.c.s
.PHONY : inc/glfw/deps/glad_gl.c.s

src/ElementBuffer.o: src/ElementBuffer.cpp.o

.PHONY : src/ElementBuffer.o

# target to build an object file
src/ElementBuffer.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ElementBuffer.cpp.o
.PHONY : src/ElementBuffer.cpp.o

src/ElementBuffer.i: src/ElementBuffer.cpp.i

.PHONY : src/ElementBuffer.i

# target to preprocess a source file
src/ElementBuffer.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ElementBuffer.cpp.i
.PHONY : src/ElementBuffer.cpp.i

src/ElementBuffer.s: src/ElementBuffer.cpp.s

.PHONY : src/ElementBuffer.s

# target to generate assembly for a file
src/ElementBuffer.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/ElementBuffer.cpp.s
.PHONY : src/ElementBuffer.cpp.s

src/Texture.o: src/Texture.cpp.o

.PHONY : src/Texture.o

# target to build an object file
src/Texture.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Texture.cpp.o
.PHONY : src/Texture.cpp.o

src/Texture.i: src/Texture.cpp.i

.PHONY : src/Texture.i

# target to preprocess a source file
src/Texture.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Texture.cpp.i
.PHONY : src/Texture.cpp.i

src/Texture.s: src/Texture.cpp.s

.PHONY : src/Texture.s

# target to generate assembly for a file
src/Texture.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/Texture.cpp.s
.PHONY : src/Texture.cpp.s

src/VertexArray.o: src/VertexArray.cpp.o

.PHONY : src/VertexArray.o

# target to build an object file
src/VertexArray.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VertexArray.cpp.o
.PHONY : src/VertexArray.cpp.o

src/VertexArray.i: src/VertexArray.cpp.i

.PHONY : src/VertexArray.i

# target to preprocess a source file
src/VertexArray.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VertexArray.cpp.i
.PHONY : src/VertexArray.cpp.i

src/VertexArray.s: src/VertexArray.cpp.s

.PHONY : src/VertexArray.s

# target to generate assembly for a file
src/VertexArray.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VertexArray.cpp.s
.PHONY : src/VertexArray.cpp.s

src/VertexBufferArray.o: src/VertexBufferArray.cpp.o

.PHONY : src/VertexBufferArray.o

# target to build an object file
src/VertexBufferArray.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VertexBufferArray.cpp.o
.PHONY : src/VertexBufferArray.cpp.o

src/VertexBufferArray.i: src/VertexBufferArray.cpp.i

.PHONY : src/VertexBufferArray.i

# target to preprocess a source file
src/VertexBufferArray.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VertexBufferArray.cpp.i
.PHONY : src/VertexBufferArray.cpp.i

src/VertexBufferArray.s: src/VertexBufferArray.cpp.s

.PHONY : src/VertexBufferArray.s

# target to generate assembly for a file
src/VertexBufferArray.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/VertexBufferArray.cpp.s
.PHONY : src/VertexBufferArray.cpp.s

src/camera.o: src/camera.cpp.o

.PHONY : src/camera.o

# target to build an object file
src/camera.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.o
.PHONY : src/camera.cpp.o

src/camera.i: src/camera.cpp.i

.PHONY : src/camera.i

# target to preprocess a source file
src/camera.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.i
.PHONY : src/camera.cpp.i

src/camera.s: src/camera.cpp.s

.PHONY : src/camera.s

# target to generate assembly for a file
src/camera.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/camera.cpp.s
.PHONY : src/camera.cpp.s

src/fileloader.o: src/fileloader.cpp.o

.PHONY : src/fileloader.o

# target to build an object file
src/fileloader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/fileloader.cpp.o
.PHONY : src/fileloader.cpp.o

src/fileloader.i: src/fileloader.cpp.i

.PHONY : src/fileloader.i

# target to preprocess a source file
src/fileloader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/fileloader.cpp.i
.PHONY : src/fileloader.cpp.i

src/fileloader.s: src/fileloader.cpp.s

.PHONY : src/fileloader.s

# target to generate assembly for a file
src/fileloader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/fileloader.cpp.s
.PHONY : src/fileloader.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/shader.o: src/shader.cpp.o

.PHONY : src/shader.o

# target to build an object file
src/shader.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shader.cpp.o
.PHONY : src/shader.cpp.o

src/shader.i: src/shader.cpp.i

.PHONY : src/shader.i

# target to preprocess a source file
src/shader.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shader.cpp.i
.PHONY : src/shader.cpp.i

src/shader.s: src/shader.cpp.s

.PHONY : src/shader.s

# target to generate assembly for a file
src/shader.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/shader.cpp.s
.PHONY : src/shader.cpp.s

src/stb.o: src/stb.cpp.o

.PHONY : src/stb.o

# target to build an object file
src/stb.cpp.o:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/stb.cpp.o
.PHONY : src/stb.cpp.o

src/stb.i: src/stb.cpp.i

.PHONY : src/stb.i

# target to preprocess a source file
src/stb.cpp.i:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/stb.cpp.i
.PHONY : src/stb.cpp.i

src/stb.s: src/stb.cpp.s

.PHONY : src/stb.s

# target to generate assembly for a file
src/stb.cpp.s:
	$(MAKE) -f CMakeFiles/main.dir/build.make CMakeFiles/main.dir/src/stb.cpp.s
.PHONY : src/stb.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... install/strip"
	@echo "... edit_cache"
	@echo "... main"
	@echo "... rebuild_cache"
	@echo "... list_install_components"
	@echo "... install/local"
	@echo "... install"
	@echo "... uninstall"
	@echo "... glfw"
	@echo "... wave"
	@echo "... simple"
	@echo "... gears"
	@echo "... boing"
	@echo "... heightmap"
	@echo "... splitview"
	@echo "... offscreen"
	@echo "... particles"
	@echo "... sharing"
	@echo "... title"
	@echo "... timeout"
	@echo "... monitors"
	@echo "... clipboard"
	@echo "... cursor"
	@echo "... msaa"
	@echo "... glfwinfo"
	@echo "... threads"
	@echo "... reopen"
	@echo "... triangle-vulkan"
	@echo "... opacity"
	@echo "... iconify"
	@echo "... gamma"
	@echo "... events"
	@echo "... icon"
	@echo "... joysticks"
	@echo "... windows"
	@echo "... empty"
	@echo "... inputlag"
	@echo "... tearing"
	@echo "... inc/glfw/deps/glad_gl.o"
	@echo "... inc/glfw/deps/glad_gl.i"
	@echo "... inc/glfw/deps/glad_gl.s"
	@echo "... src/ElementBuffer.o"
	@echo "... src/ElementBuffer.i"
	@echo "... src/ElementBuffer.s"
	@echo "... src/Texture.o"
	@echo "... src/Texture.i"
	@echo "... src/Texture.s"
	@echo "... src/VertexArray.o"
	@echo "... src/VertexArray.i"
	@echo "... src/VertexArray.s"
	@echo "... src/VertexBufferArray.o"
	@echo "... src/VertexBufferArray.i"
	@echo "... src/VertexBufferArray.s"
	@echo "... src/camera.o"
	@echo "... src/camera.i"
	@echo "... src/camera.s"
	@echo "... src/fileloader.o"
	@echo "... src/fileloader.i"
	@echo "... src/fileloader.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/shader.o"
	@echo "... src/shader.i"
	@echo "... src/shader.s"
	@echo "... src/stb.o"
	@echo "... src/stb.i"
	@echo "... src/stb.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

